### 선물 (Futures Contract)
  + 미래에 필요한 상품을 미리 거래하는 것
  + 거래를 할 때(거래일) 바로 상품이 넘어가지 않고 약속한 날짜(만기일)가 되어야 상품이 넘어감
  + 그러므로 상대방의 신용이 중요 (거래소 보증 O = 선물거래 / 거래소 보증 X = 선도거래)
  + 대표적인 선물 상품: WTI (서부 텍사스 중질유)

#### 선물거래의 특징
  - 시작부터 매도할 수 있음 (팔 물건이 없어도 매도가 가능)
  - 선물가격
    * 승수(Multiplier): 선물 1계약당 가격을 결정하는 것
    * 선물가격 = 기초자산지수(가격) * 승수 * 계약 수
  - 증거금만 있으면 거래가능 (레버리지 효과)
    * 선물계약은 기본적으로 후불 / 하지만 불특정 다수 간의 거래에 따른 부도 위험에 대비해 계약시점에 보증금 성격의 보증금 부여
    * 예) KOSPI200 지수선물의 위탁증거금율 = 7.5%, KOSPI200 = 300, 승수 = 250,000원이라면...  
      + KOSPI200 선물 1계약에 해당하는 증거금은 5,625,000원 (지수 * 계약 수 * 승수 * 증거금율 = 300 * 1 * 250,000 * 7.5%)
      + 승수에 따라 레버리지 가능해짐 (레버리지: 상대적으로 적은 자본으로 큰 규모의 매매를 하는 것)
    * 증거금율은 거래소가 정하고, 시장 상황에 따라 수시로 변경 (시장 가격 변동에 따른 위험에 따라)
  - 레버리지에 대한 안전장치: 일일정산과 마진콜
    * 거래 상대방이 계약을 이행하지 않을 위험 = 거래상대방 위험 --> 선물거래는 이를 방지하기 위해 매일 정산 (일일정산)
    * 유지증거금 제도: KOSPI200 선물의 유지증거금율이 5%일 때, 증거금이 선물계약 금액의 5% 미만으로 내려가면 투자자에게 위탁증거금만큼인 7.5%에 맞추도록 돈을 추가로 납부하게 하는 제도 --> 추가 납부를 안하면 거래소에서 투자자 포지션 청산 (마진콜)

#### 선물 이론가
  + 파생상품 밸류에이션 => 파생상품을 보유하고 있을 때와 보유하고 있지 않을 때의 손익을 따져서 결정
    - 선물도 마찬가지 => 계약 체결 후 만기가 되어 상품을 인도받을 때까지 손익을 따져보면 됨
  + 계산은 나중 ==> 이자이익 발생 (포트폴리오상의 포지션에는 有, 돈은 지불하지 않은 상태)
  + 확보 자산에 대한 권리 X ==> 배당 X
  + 선물 이론가 계산:
    - 선물 이론가 = 기초자산 가격 + 금융(이자) 비용 - 배당 수입
    - 연속복리이자율(Continuous Compounded Interest Rate) 이용하여 표현... 
      * $ F = Se^{(r-d)t} $
      * $ F = S[1+(r-d)*t/365]$ (단순이자율 활용한 공식)
      * F: 선물가격, S: 현물가격, r: 이자율, d: 배당률, t: 잔존만기


#### Numpy
  + 다차원 배열을 다루고 벡터 연산법을 알아본다.

In [1]:
import numpy as np

In [2]:
# 1차원 array 만들기
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [3]:
# 2차원 array 만들기: 이중 [[]]
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3차원 array 만들기: 3중 [[[]]]
a3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
# np.arange(시작번호, 끝번호, 간격)로 배열 모양 정의
c = np.arange(15) # 시작번호와 간격을 생략하면 0부터 시작해서 1씩 올라가며 숫자를 돌려줌
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
# np.reshape(행,열)으로 배열 모양 변경
c = c.reshape(3,5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
d = np.arange(0,100,5)
print(d)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [8]:
d = d.reshape(2,2,5)
print(d)

[[[ 0  5 10 15 20]
  [25 30 35 40 45]]

 [[50 55 60 65 70]
  [75 80 85 90 95]]]


In [9]:
# 배열의 스칼라 연산
n1 = np.array([[1,0],
              [0,1]])
n2 = np.array([[1,2],
              [3,4]])

In [10]:
n1+n2

array([[2, 2],
       [3, 5]])

In [11]:
n1-n2

array([[ 0, -2],
       [-3, -3]])

In [12]:
n1*n2

array([[1, 0],
       [0, 4]])

In [13]:
n1/n2

array([[1.  , 0.  ],
       [0.  , 0.25]])

In [14]:
n2/n1

<ipython-input-14-3c9af8f1022c>:1: RuntimeWarning: divide by zero encountered in true_divide
  n2/n1


array([[ 1., inf],
       [inf,  4.]])

In [15]:
# 배열 전체에 같은 연산을 일괄적으로 적용
n1+1

array([[2, 1],
       [1, 2]])

In [16]:
n1-1

array([[ 0, -1],
       [-1,  0]])

In [17]:
n1*2

array([[2, 0],
       [0, 2]])

In [18]:
n1/2

array([[0.5, 0. ],
       [0. , 0.5]])

##### 벡터 곱셈
$ \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
\begin{bmatrix}
e & f \\
g & h
\end{bmatrix}
=
 \begin{bmatrix}
ae + bg & af + bh \\
ce + dg & cf +dh
\end{bmatrix}$

In [19]:
# numpy에서는 dot()함수 사용
np.dot(n1,n2)

array([[1, 2],
       [3, 4]])

In [20]:
n1.dot(n2) # np.dot(n1,n2)와 같은 표현

array([[1, 2],
       [3, 4]])

In [21]:
# 행끼리, 열끼리 계산의 장점 --> 최고가, 최저가, 평균가 등을 뽑을 때 유리
# axis=0 => 열끼리 / axis=1 => 행끼리
n3 = np.arange(12).reshape(3,4)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
n3.sum(axis=0) # 열 합계

array([12, 15, 18, 21])

In [23]:
n3.sum(axis=1) # 행 합계

array([ 6, 22, 38])

In [24]:
n3.max(axis=0) # 각 열의 최댓값

array([ 8,  9, 10, 11])

In [25]:
n3.mean(axis=1) # 각 행의 평균값

array([1.5, 5.5, 9.5])

In [26]:
# 축 지정 X --> 전체 원소에 대한 연산 실행
print(n3.max())
print(n3.min())
print(n3.sum())
print(n3.mean())
print(n3.std()) # 표준편차
print(n3.var()) # 분산
print(n3.cumsum()) # 각 원소의 누적 합
print(n3.cumprod()) # 각 원소의 누적 곱

11
0
66
5.5
3.452052529534663
11.916666666666666
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
# 배열에서 특정 데이터 뽑아오기 => 슬라이싱
# 첫 번째 데이터 => 1이 아닌 0부터 시작
v = np.array([[11,12,13,14,15],
            [21,22,23,24,25],
            [31,32,33,34,35],
            [41,42,43,44,45]])

In [28]:
v[1,2] # 2행 3열 데이터 추출

23

In [29]:
v[1][2] # v[1,2]와 동일

23

In [30]:
v[:,1] # 전체 행, 2열 데이터 추출

array([12, 22, 32, 42])

In [31]:
v[1:3,1] # 2~3행, 2열 데이터 추출

array([22, 32])

In [32]:
v[1,:] # 2행, 전체 절 데이터 추출

array([21, 22, 23, 24, 25])

#### Pandas
  + pandas로... 1차원 데이터 => 시리즈, 2차원 데이터 => 데이터프레임

In [33]:
import pandas as pd

In [34]:
# 주가를 담아놓은 리스트 생성
prices = [1000,1010,1020]

In [35]:
# pd.date_range('시작날짜','끝 날짜',periods=날짜 수,freq='주기') (끝 날짜 혹은 periods 둘 중 하나 지정 / freq는 생략가능)
# freq --> 'D'(매일) / 'W'(매주) / 'M'(매달) 등으로 지정, 생략 시 기본값 'D'
dates = pd.date_range('20181201',periods=3)
dates

DatetimeIndex(['2018-12-01', '2018-12-02', '2018-12-03'], dtype='datetime64[ns]', freq='D')

In [36]:
pd.date_range('20200101','20200131',freq='W')

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26'], dtype='datetime64[ns]', freq='W-SUN')

In [37]:
s = pd.Series(prices, index=dates) # 주가를 데이터, 날짜를 인덱스로 하는 시리즈 생성
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, dtype: int64

In [38]:
s2 = pd.Series(prices)
s2

0    1000
1    1010
2    1020
dtype: int64

In [39]:
s2[3] = 1030 # 시리즈에 데이터 추가
s2

0    1000
1    1010
2    1020
3    1030
dtype: int64

In [40]:
# str과 int의 차이
print('123'+'123')
print(123+123)

123123
246


In [41]:
# pd.to_datetime('날짜') => str 형식의 날짜를 datetime으로 변환
s[pd.to_datetime('2018-12-04')] = 1030
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
2018-12-04    1030
Freq: D, dtype: int64

In [42]:
s[2] # 리스트나 배열처럼 특정 데이터 추출 가능

1020

In [43]:
s['2018-12-03'] # 레이블(인덱스 이름)을 이용하여 추출도 가능

1020

In [44]:
# 데이터프레임 생성
prices = {'A전자': [1000,1010,1020],
         'B화학': [2000,2010,2020],
         'C금융': [3000,3010,3020]}
df1 = pd.DataFrame(prices)
df1

A전자   B화학   C금융
0  1000  2000  3000
1  1010  2010  3010
2  1020  2020  3020

In [45]:
# 인덱스 추가
df2 = pd.DataFrame(prices, index=dates)
df2

A전자   B화학   C금융
2018-12-01  1000  2000  3000
2018-12-02  1010  2010  3010
2018-12-03  1020  2020  3020

In [46]:
# 데이터프레임.iloc[줄번호, 열번호(생략기능, 생략하면 열 전체)] 데이터프레임 조회
df2.iloc[0]

A전자    1000
B화학    2000
C금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [47]:
df2.iloc[:,0]

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [48]:
df2.iloc[0,0]

1000

In [49]:
# 데이터프레임.loc['행 레이블','열 레이블']
df2.loc['2018-12-01']

A전자    1000
B화학    2000
C금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [50]:
df2.loc[:,'A전자']

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [51]:
df2.loc['2018-12-02','B화학']

2010

In [52]:
df2.A전자 # df2['A전자']와 동일

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [53]:
df2['A전자']['2018-12-01'] # 열 선택 후 행 선택

1000

In [54]:
df2.loc[:,'A전자']['2018-12-01'] # df2['A전자']['2018-12-01']와 동일

1000

In [55]:
# 데이터프레임에 데이터 추가
df2['D엔터'] = [4000,4010,4020]
df2

A전자   B화학   C금융   D엔터
2018-12-01  1000  2000  3000  4000
2018-12-02  1010  2010  3010  4010
2018-12-03  1020  2020  3020  4020

In [56]:
df2['E텔레콤'] = s
df2

A전자   B화학   C금융   D엔터  E텔레콤
2018-12-01  1000  2000  3000  4000  1000
2018-12-02  1010  2010  3010  4010  1010
2018-12-03  1020  2020  3020  4020  1020

In [57]:
# pd.concat(A, B, axis=1) => 데이터프레임 병합
# 시리즈를 이용해 인덱스에 업는 값도 추가하려면 사용 --> 데이터프레임 확장
# axis는 합쳐질 방향 (0=행, 1=열)
s.name = 'F소프트'
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
2018-12-04    1030
Freq: D, Name: F소프트, dtype: int64

In [58]:
df2 = pd.concat([df2,s],axis=1)
df2

A전자     B화학     C금융     D엔터    E텔레콤  F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030

In [59]:
# 만약 12.7의 시세가 12.1보다 50원씩 올랐다면
df3 = df2.iloc[0]
df3 = df3 + 60
df3.name = pd.to_datetime('20181207')
df3

A전자     1060.0
B화학     2060.0
C금융     3060.0
D엔터     4060.0
E텔레콤    1060.0
F소프트    1060.0
Name: 2018-12-07 00:00:00, dtype: float64

In [61]:
df2 = df2.append(df3)
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [62]:
# 만약 12.6의 시세가 12.1보다 50원씩 올랐다면
df3 = df2.iloc[0] + 50
df3.name = pd.to_datetime('20181206')
df2 = df2.append(df3)
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0

In [64]:
# 데이터프레임.sort_index(axis=0, ascending=True) => 인덱스 정렬
# ascending --> True = 오름차순, False = 내림차순, 생략가능
df2 = df2.sort_index(axis=0)
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [65]:
# 데이터프레임.drop(label, axis=0) => 데이터프레임에서 행 또는 열 삭제
# 여기서 인덱스 값의 형태는 datetime이므로 pd.to_datetime()으로 지정하여야 함
df2.drop(pd.to_datetime('2018-12-06'))

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [68]:
# 여러 행 삭제
df2.drop([pd.to_datetime('2018-12-02'),pd.to_datetime('2018-12-06')])

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [69]:
df2.drop('D엔터',axis=1) # 열 삭제

A전자     B화학     C금융    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  3050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  1060.0  1060.0

In [70]:
df2.drop(['C금융','E텔레콤'], axis=1)

A전자     B화학     D엔터    F소프트
2018-12-01  1000.0  2000.0  4000.0  1000.0
2018-12-02  1010.0  2010.0  4010.0  1010.0
2018-12-03  1020.0  2020.0  4020.0  1020.0
2018-12-04     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  4050.0  1050.0
2018-12-07  1060.0  2060.0  4060.0  1060.0

In [71]:
# 보간법 --> 구멍 메우기
# 데이터프레임.dropna() => NaN이 포함된 행 삭제
df2.dropna()

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [72]:
# 데이터프레임.fillna(대체값 또는 방법) => NaN을 다른 값으로 대체
df2.fillna(0)

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     0.0     0.0     0.0     0.0     0.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [73]:
df2.fillna(method='ffill') # NaN을 앞의 값으로 채움 (forward fill)

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04  1020.0  2020.0  3020.0  4020.0  1020.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [74]:
df2.fillna(method='bfill') # NaN을 뒤의 값으로 채움 (backward fill)

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04  1050.0  2050.0  3050.0  4050.0  1050.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [ ]:
# 이와 같은 기술을 활용하여 모델링을 해본다